#!/usr/bin/env python3
"""
Simple demo showing the knowledge graph structure
"""

def show_simple_graph():
    print("=" * 70)
    print("KNOWLEDGE GRAPH STRUCTURE & VISUALIZATION")
    print("=" * 70)
    
    print("\n1. GRAPH NODES (Issues):")
    print("-" * 40)
    print("REDDIT NODES:")
    print("- Node ID: reddit_001")
    print("- Title: BART delays causing major commute issues")
    print("- Source: reddit")
    print("- Location: SOMA, San Francisco")
    print("- Severity: high")
    print("- Keywords: [transportation, BART, delays]")
    print("- Metadata: {subreddit: sftransportation, score: 25}")
    print()
    print("SF311 NODES:")
    print("- Node ID: sf311_001")
    print("- Title: Graffiti")
    print("- Source: 311")
    print("- Location: Mission District, San Francisco")
    print("- Severity: medium")
    print("- Keywords: [graffiti, vandalism, commercial]")
    print("- Metadata: {offense_type: Graffiti, coordinates: (37.7651, -122.4190)}")
    
    print("\n2. GRAPH EDGES (Relationships):")
    print("-" * 40)
    print("GEOGRAPHIC RELATIONSHIPS:")
    print("- reddit_001 <-> sf311_002 (same neighborhood: SOMA)")
    print("- Strength: 0.73")
    print("- Type: geographic")
    print("- Reason: Both issues in SOMA area")
    print()
    print("TEMPORAL RELATIONSHIPS:")
    print("- reddit_003 <-> sf311_004 (reported same week)")
    print("- Strength: 0.65")
    print("- Type: temporal")
    print("- Reason: Issues reported around same time")
    print()
    print("SIMILARITY RELATIONSHIPS:")
    print("- sf311_001 <-> sf311_005 (both graffiti issues)")
    print("- Strength: 0.89")
    print("- Type: similar")
    print("- Reason: Same issue type and description")
    
    print("\n3. GRAPH CLUSTERS:")
    print("-" * 40)
    print("TRANSPORTATION CLUSTER:")
    print("- Nodes: reddit_001, sf311_002, reddit_006")
    print("- Common themes: [BART, delays, commute, parking]")
    print("- Geographic: SOMA, Mission District")
    print("- Severity: high (1), medium (2)")
    print()
    print("GRAFFITI CLUSTER:")
    print("- Nodes: sf311_001, sf311_005, reddit_007")
    print("- Common themes: [graffiti, vandalism, commercial]")
    print("- Geographic: Mission District, Castro")
    print("- Severity: medium (3)")
    print()
    print("HOMELESSNESS CLUSTER:")
    print("- Nodes: reddit_003, sf311_004, reddit_008")
    print("- Common themes: [homeless, encampment, tent, shelter]")
    print("- Geographic: Tenderloin, Mission District")
    print("- Severity: high (1), medium (2)")
    
    print("\n4. GRAPH VISUALIZATION:")
    print("-" * 40)
    print("KNOWLEDGE GRAPH STRUCTURE:")
    print()
    print("REDDIT NODES (Community Discussions)")
    print("reddit_001: BART delays [SOMA, Transportation, HIGH]")
    print("     |")
    print("     | Geographic (0.73)")
    print("     |")
    print("sf311_002: Parking [SOMA, Parking, MEDIUM]")
    print("     |")
    print("     | Temporal (0.65)")
    print("     |")
    print("reddit_003: Homeless [Mission, Homeless, HIGH]")
    print("     |")
    print("     | Similar (0.89)")
    print("     |")
    print("sf311_004: Cleaning [Mission, Litter, LOW]")
    print()
    print("CLUSTERS:")
    print("Transportation Cluster    Graffiti Cluster      Homelessness Cluster")
    print("3 nodes                  3 nodes               3 nodes")
    print("SOMA + Mission           Mission + Castro       Tenderloin + Mission")
    print("High severity            Medium severity        High + Medium severity")
    
    print("\n5. GRAPH QUERY EXAMPLES:")
    print("-" * 40)
    print("SPATIAL QUERIES:")
    print("- Show all issues in Mission District")
    print("- Find issues within 1 mile of coordinates (37.7749, -122.4194)")
    print("- Get hotspots by neighborhood")
    print()
    print("TEMPORAL QUERIES:")
    print("- Show issues reported in the last week")
    print("- Find issues that occurred around the same time")
    print("- Get trending issues over time")
    print()
    print("SIMILARITY QUERIES:")
    print("- Find issues similar to graffiti")
    print("- Show related transportation problems")
    print("- Get issues with similar severity")
    print()
    print("CLUSTER QUERIES:")
    print("- Show all issues in the transportation cluster")
    print("- Find the largest issue cluster")
    print("- Get cluster patterns and themes")
    
    print("\n6. GRAPH METRICS:")
    print("-" * 40)
    print("NODE METRICS:")
    print("- Total nodes: 50 (25 Reddit + 25 SF311)")
    print("- Node types: transportation, graffiti, homelessness, etc.")
    print("- Severity distribution: high (10), medium (25), low (15)")
    print("- Geographic coverage: 8 SF neighborhoods")
    print()
    print("EDGE METRICS:")
    print("- Total relationships: 75")
    print("- Geographic relationships: 30 (40%)")
    print("- Temporal relationships: 20 (27%)")
    print("- Similarity relationships: 25 (33%)")
    print("- Average relationship strength: 0.72")
    print()
    print("CLUSTER METRICS:")
    print("- Total clusters: 5")
    print("- Largest cluster: Transportation (8 nodes)")
    print("- Most connected node: sf311_001 (6 relationships)")
    print("- Cluster density: 0.65")

if __name__ == "__main__":
    show_simple_graph()
